server {
    listen 80;
    server_name starfellharbor.mooo.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name starfellharbor.mooo.com;

    ssl_certificate /etc/letsencrypt/live/starfellharbor.mooo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/starfellharbor.mooo.com/privkey.pem;

    location / {
        root  /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        root    /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}